### ISSUE TITLE
Versioning mismatch

### ISSUE THREAD

**Issue by emipa606** [petripaavola/IntuneDeviceDetailsGUI#11]
The latest version is defined as 2.98 but the last version before that was 2.974.
I assume that you meant 2.980?

**Comment by petripaavola** [comment]
Yes I may have been a little bit lazy and shortened the version originally with latest update :)

I just few minutes ago updated newest version to 2.982 so now it should be ok.

**Comment by emipa606** [comment]
My update checker got confused, great to hear its fixed already!

**Comment by NekoJonez** [comment]
I think this issue can be closed now? ;)
