### ISSUE TITLE
"No LAPS password found for this device"

### ISSUE THREAD

**Issue by BirbObserb** [petripaavola/IntuneDeviceDetailsGUI#15]
In the GUI, the LAPS password tab says "No LAPS password found for this device," but the password exists and is obtainable via Entra/Intune. Any ideas? 

Fantastic app, by the way.

**Comment by freeyland** [comment]
I have the same issue:

Get Windows LAPS Password information
Invoke-MSGraphGetRequestWithMSGraphAllPages : There was error with MGGraphRequest with url https://graph.microsoft.com/
v1.0/directory/deviceLocalCredentials/xxxxxxxxxxxxxxxxxxxxxxxxx?$select=credentials!
At xxxxxxxxxxxxxxxxxx \IntuneDeviceDetailsGUI.ps1:2911 char:25
+ ... indowsLAPSPassword = Invoke-MSGraphGetRequestWithMSGraphAllPages $uri
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-MSGraphGetRequestWithMSGraphAll
   Pages

**Comment by freeyland** [comment]
Has to do with access permissions. I could run the query in graph explorer without issues.

**Comment by petripaavola** [comment]
Yes I can confirm the issue was Graph API permissions. I had forgot to add scope DeviceLocalCredential.Read.All to Graph API.

I added scope and updated script to version 2.985. If you download newest version you should get Graph API permissions update question when logging in and then LAPS passwords should work.

Can you confirm that this fixed your issue?

**Comment by BirbObserb** [comment]
I can confirm that fixed it. Sorry this took a bit to get back to, due to being in the midst of global Crowdstrike hell. 

Thanks very much for your efforts in making our Intune lives better!
