### ISSUE TITLE
Tool no longer works

### ISSUE THREAD

**Issue by ThariqM083** [petripaavola/IntuneDeviceDetailsGUI#7]
Hi Petri, Awesome tool which has helped our support teams, unfortunately since MS have dropped the old msgraph enterprise app, a lot of the code no longer works. Are you rewriting this tool using mggraph cmdlets

**Comment by ThariqM083** [comment]
Thanks, Petri, I appreciate the response!

**Comment by petripaavola** [comment]
I just uploaded version 2.98 which uses Microsoft.Graph.Authentication module.

Script now also shows Bitlocker Recovery Keys and Windows LAPS Password.

Can you check that you get script working in your environment?

**Comment by ThariqM083** [comment]
Awesome Work ! 

We have tested the tool and is working as expected. It does seem to be a little bit slower than the original one. But your efforts are  really appreciated !

**Comment by petripaavola** [comment]
I might try to improve script a little bit more by using Graph API batch processing. But it's always choice between fixing existing script or creating new features. And new features usually win.

But once I get batch request work generally to any request then it might speed up the script quite a lot. Script already uses batch processing in some part of the script but not generally to all Graph API requests.
