### ISSUE TITLE
broken sign in

### ISSUE THREAD

**Issue by henrikmai** [petripaavola/IntuneDeviceDetailsGUI#8]
See here: https://learn.microsoft.com/en-us/answers/questions/1659638/weve-detected-a-microsoft-intune-powershell-script

**Comment by petripaavola** [comment]
Download latest 2.98 version of the script which now uses Microsoft Graph module for Graph API requests.

Install new module with command:

Install-Module -Name Microsoft.Graph.Authentication -Scope CurrentUser

**Comment by henrikmai** [comment]
thats what i did, but it didn´t work.

i fixed it like in the link i posted.

keep in mind, only if someone asks later
